import { Team } from './bracket.types';

export const TEAMS: Team[] = [
  { name: 'Air Force', primary: '#003087', secondary: '#8A8D8F', textColor: 'white' },
  { name: 'Akron', primary: '#041E42', secondary: '#A89968', textColor: 'white' },
  { name: 'Alabama', primary: '#9E1B32', secondary: '#828A8F', textColor: 'white' },
  { name: 'Appalachian State', primary: '#FFB612', secondary: '#000000', textColor: 'black' },
  { name: 'Arizona', primary: '#CC0033', secondary: '#003366', textColor: 'white' },
  { name: 'Arizona State', primary: '#8C1D40', secondary: '#FFC627', textColor: 'white' },
  { name: 'Arkansas', primary: '#9D2235', secondary: '#000000', textColor: 'white' },
  { name: 'Arkansas State', primary: '#CC0000', secondary: '#000000', textColor: 'white' },
  { name: 'Army', primary: '#F1B82D', secondary: '#000000', textColor: 'black' },
  { name: 'Auburn', primary: '#0C2340', secondary: '#E87722', textColor: 'white' },
  { name: 'Ball State', primary: '#BA0C2F', secondary: '#000000', textColor: 'white' },
  { name: 'Baylor', primary: '#154734', secondary: '#FFB81C', textColor: 'white' },
  { name: 'Boise State', primary: '#0033A0', secondary: '#D64309', textColor: 'white' },
  { name: 'Boston College', primary: '#98012E', secondary: '#D4A017', textColor: 'white' },
  { name: 'Bowling Green', primary: '#4B3800', secondary: '#F75000', textColor: 'white' },
  { name: 'Buffalo', primary: '#005BBB', secondary: '#000000', textColor: 'white' },
  { name: 'BYU', primary: '#002E5D', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'California', primary: '#003262', secondary: '#FDB515', textColor: 'white' },
  { name: 'Central Michigan', primary: '#6A0032', secondary: '#FFC82E', textColor: 'white' },
  { name: 'Charlotte', primary: '#005035', secondary: '#B3A369', textColor: 'white' },
  { name: 'Cincinnati', primary: '#E00122', secondary: '#000000', textColor: 'white' },
  { name: 'Clemson', primary: '#F66733', secondary: '#522D80', textColor: 'white' },
  { name: 'Coastal Carolina', primary: '#006F71', secondary: '#A27752', textColor: 'white' },
  { name: 'Colorado', primary: '#CFB87C', secondary: '#000000', textColor: 'black' },
  { name: 'Colorado State', primary: '#1E4D2B', secondary: '#C8C372', textColor: 'white' },
  { name: 'Duke', primary: '#003087', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'East Carolina', primary: '#4B1869', secondary: '#FDC82F', textColor: 'white' },
  { name: 'Eastern Michigan', primary: '#006028', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Florida', primary: '#0021A5', secondary: '#FA4616', textColor: 'white' },
  { name: 'Florida Atlantic', primary: '#003366', secondary: '#CC0000', textColor: 'white' },
  { name: 'Florida International', primary: '#081E3F', secondary: '#B6862C', textColor: 'white' },
  { name: 'Florida State', primary: '#782F40', secondary: '#CEB888', textColor: 'white' },
  { name: 'Fresno State', primary: '#CC0033', secondary: '#002E6D', textColor: 'white' },
  { name: 'Georgia', primary: '#BA0C2F', secondary: '#000000', textColor: 'white' },
  { name: 'Georgia Southern', primary: '#011E41', secondary: '#C1A875', textColor: 'white' },
  { name: 'Georgia State', primary: '#0039A6', secondary: '#CC0000', textColor: 'white' },
  { name: 'Georgia Tech', primary: '#B3A369', secondary: '#003057', textColor: 'black' },
  { name: "Hawai'i", primary: '#024731', secondary: '#C8A323', textColor: 'white' },
  { name: 'Houston', primary: '#C8102E', secondary: '#63666A', textColor: 'white' },
  { name: 'Illinois', primary: '#E84A27', secondary: '#13294B', textColor: 'white' },
  { name: 'Indiana', primary: '#990000', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Iowa', primary: '#FFCD00', secondary: '#000000', textColor: 'black' },
  { name: 'Iowa State', primary: '#C8102E', secondary: '#F1BE48', textColor: 'white' },
  { name: 'James Madison', primary: '#450084', secondary: '#CBB677', textColor: 'white' },
  { name: 'Jax State', primary: '#CC0000', secondary: '#003087', textColor: 'white' },
  { name: 'Kansas', primary: '#0051A5', secondary: '#E8000D', textColor: 'white' },
  { name: 'Kansas State', primary: '#512888', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Kennesaw State', primary: '#FDBB30', secondary: '#000000', textColor: 'black' },
  { name: 'Kent State', primary: '#002664', secondary: '#EAAA00', textColor: 'white' },
  { name: 'Kentucky', primary: '#0033A0', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Liberty', primary: '#002868', secondary: '#C41230', textColor: 'white' },
  { name: 'Louisiana', primary: '#CC0000', secondary: '#000000', textColor: 'white' },
  { name: 'Louisiana Tech', primary: '#002F6C', secondary: '#E31B23', textColor: 'white' },
  { name: 'Louisville', primary: '#AD0000', secondary: '#000000', textColor: 'white' },
  { name: 'LSU', primary: '#461D7C', secondary: '#FDD023', textColor: 'white' },
  { name: 'Marshall', primary: '#00B140', secondary: '#000000', textColor: 'white' },
  { name: 'Maryland', primary: '#E03a3e', secondary: '#FFD520', textColor: 'white' },
  { name: 'Memphis', primary: '#003087', secondary: '#898D8D', textColor: 'white' },
  { name: 'Miami', primary: '#005030', secondary: '#F47321', textColor: 'white' },
  { name: 'Miami University', primary: '#C3142D', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Michigan', primary: '#00274C', secondary: '#FFCB05', textColor: 'white' },
  { name: 'Michigan State', primary: '#18453B', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Middle Tennessee St', primary: '#0066CC', secondary: '#000000', textColor: 'white' },
  { name: 'Minnesota', primary: '#7A0019', secondary: '#FFCC33', textColor: 'white' },
  { name: 'Mississippi State', primary: '#660000', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Missouri', primary: '#F1B82D', secondary: '#000000', textColor: 'black' },
  { name: 'Navy', primary: '#00205B', secondary: '#C5B783', textColor: 'white' },
  { name: 'NC State', primary: '#CC0000', secondary: '#000000', textColor: 'white' },
  { name: 'Nebraska', primary: '#E41C38', secondary: '#000000', textColor: 'white' },
  { name: 'Nevada', primary: '#003366', secondary: '#807B79', textColor: 'white' },
  { name: 'New Mexico', primary: '#BA0C2F', secondary: '#63666A', textColor: 'white' },
  { name: 'New Mexico State', primary: '#8C1515', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'North Carolina', primary: '#4B9CD3', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'North Texas', primary: '#00853E', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Northern Illinois', primary: '#CC0000', secondary: '#000000', textColor: 'white' },
  { name: 'Northwestern', primary: '#4E2A84', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Notre Dame', primary: '#0C2340', secondary: '#C99700', textColor: 'white' },
  { name: 'Ohio', primary: '#00694E', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Ohio State', primary: '#BB0000', secondary: '#666666', textColor: 'white' },
  { name: 'Oklahoma', primary: '#841617', secondary: '#FDF9D8', textColor: 'white' },
  { name: 'Oklahoma State', primary: '#FF7300', secondary: '#000000', textColor: 'white' },
  { name: 'Old Dominion', primary: '#003057', secondary: '#A4C8E1', textColor: 'white' },
  { name: 'Ole Miss', primary: '#CE1126', secondary: '#14213D', textColor: 'white' },
  { name: 'Oregon', primary: '#154733', secondary: '#FEE123', textColor: 'white' },
  { name: 'Oregon State', primary: '#DC4405', secondary: '#000000', textColor: 'white' },
  { name: 'Penn State', primary: '#041E42', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Pittsburgh', primary: '#003594', secondary: '#FFB81C', textColor: 'white' },
  { name: 'Purdue', primary: '#CEB888', secondary: '#000000', textColor: 'black' },
  { name: 'Rice', primary: '#002469', secondary: '#C1A875', textColor: 'white' },
  { name: 'Rutgers', primary: '#CC0033', secondary: '#5F6A72', textColor: 'white' },
  { name: 'Sam Houston', primary: '#F18A00', secondary: '#001F5B', textColor: 'white' },
  { name: 'San Diego State', primary: '#A6192E', secondary: '#000000', textColor: 'white' },
  { name: 'San Jose State', primary: '#0055A2', secondary: '#E5A823', textColor: 'white' },
  { name: 'SMU', primary: '#0033A0', secondary: '#C8102E', textColor: 'white' },
  { name: 'South Alabama', primary: '#00205B', secondary: '#BF0D3E', textColor: 'white' },
  { name: 'South Carolina', primary: '#73000A', secondary: '#000000', textColor: 'white' },
  { name: 'Southern Mississippi', primary: '#000000', secondary: '#FFC845', textColor: 'white' },
  { name: 'Stanford', primary: '#8C1515', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Syracuse', primary: '#F76900', secondary: '#002147', textColor: 'white' },
  { name: 'TCU', primary: '#4D1979', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Temple', primary: '#9D2235', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Tennessee', primary: '#FF8200', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Texas', primary: '#BF5700', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Texas A&M', primary: '#500000', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Texas State', primary: '#461D7C', secondary: '#C0A951', textColor: 'white' },
  { name: 'Texas Tech', primary: '#CC0000', secondary: '#000000', textColor: 'white' },
  { name: 'Toledo', primary: '#003366', secondary: '#FFC72C', textColor: 'white' },
  { name: 'Troy', primary: '#8B0000', secondary: '#5C4827', textColor: 'white' },
  { name: 'Tulane', primary: '#006747', secondary: '#418FDE', textColor: 'white' },
  { name: 'Tulsa', primary: '#002D62', secondary: '#C8102E', textColor: 'white' },
  { name: 'UAB', primary: '#1E6B52', secondary: '#FFC82E', textColor: 'white' },
  { name: 'UCF', primary: '#000000', secondary: '#BA9B37', textColor: 'white' },
  { name: 'UCLA', primary: '#2D68C4', secondary: '#F2A900', textColor: 'white' },
  { name: 'UConn', primary: '#000E2F', secondary: '#E4002B', textColor: 'white' },
  { name: 'UL Monroe', primary: '#800000', secondary: '#B0965A', textColor: 'white' },
  { name: 'UMass', primary: '#971B2F', secondary: '#000000', textColor: 'white' },
  { name: 'UNLV', primary: '#CF0A2C', secondary: '#808080', textColor: 'white' },
  { name: 'USC', primary: '#990000', secondary: '#FFC72C', textColor: 'white' },
  { name: 'USF', primary: '#006747', secondary: '#CFC493', textColor: 'white' },
  { name: 'Utah', primary: '#CC0000', secondary: '#000000', textColor: 'white' },
  { name: 'Utah State', primary: '#0F1C3F', secondary: '#8B9DCE', textColor: 'white' },
  { name: 'UTEP', primary: '#FF8200', secondary: '#041E42', textColor: 'white' },
  { name: 'UTSA', primary: '#002A5C', secondary: '#F15A22', textColor: 'white' },
  { name: 'Vanderbilt', primary: '#866D4B', secondary: '#000000', textColor: 'white' },
  { name: 'Virginia', primary: '#232D4B', secondary: '#F84C1E', textColor: 'white' },
  { name: 'Virginia Tech', primary: '#630031', secondary: '#CF4420', textColor: 'white' },
  { name: 'Wake Forest', primary: '#9E7E38', secondary: '#000000', textColor: 'white' },
  { name: 'Washington', primary: '#33006F', secondary: '#E8D3A2', textColor: 'white' },
  { name: 'Washington State', primary: '#981E32', secondary: '#5E6A71', textColor: 'white' },
  { name: 'West Virginia', primary: '#002855', secondary: '#EAAA00', textColor: 'white' },
  { name: 'Western Kentucky', primary: '#C60C30', secondary: '#000000', textColor: 'white' },
  { name: 'Western Michigan', primary: '#6C4023', secondary: '#D4A017', textColor: 'white' },
  { name: 'Wisconsin', primary: '#C5050C', secondary: '#FFFFFF', textColor: 'white' },
  { name: 'Wyoming', primary: '#492F24', secondary: '#FFC425', textColor: 'white' },
];

export const TEAM_MAP: Record<string, Team> = TEAMS.reduce((acc, team) => {
  acc[team.name] = team;
  return acc;
}, {} as Record<string, Team>);

export const getTeam = (name: string | null): Team | null => {
  if (!name) return null;
  return TEAM_MAP[name] ?? null;
};

export const TEAM_NAMES = TEAMS.map((t) => t.name);
